### ISSUE TITLE
Modifying const data

### ISSUE THREAD

**Issue by pinepain** [colder/php-weakref#21]
From [wr_store.c:L91](https://github.com/colder/php-weakref/blob/5f758576869623581dedd92098689213dfa0a9f8/wr_store.c#L91):

``` C
((zend_object_handlers *)ref_obj->handlers)->dtor_obj = wr_store_tracked_object_dtor;
```

but handlers specified as `const zend_object_handlers *handlers` and modifying pointer to const value is something that specified as an undefined behavior.

Can you pleas clarify what is the reason do cast away constness apart of having handlers pointer value the same so `spl_object_hash()` will also be the same?

**Comment by colder** [comment]
This is indeed a tad bit hackish, because we cast the const away.

The alternative would be to replace the entire handlers struct (I'm guessing that's what you do?) but as you point out this means that spl_object_hash is no longer stable.

I would say that affecting the return value of spl_object_hash in an observable way is a big no-no. A solution would be for weakref to replace the implementation of spl_object_hash so that it returns the hash with respect to the old handlers pointer. That would work I guess but it seems almost more hackish that casting the const away.

**Comment by pinepain** [comment]
Yes, this is what I do. I thought about replacinf `spl_object_hash()` by own implementation, but I don't think it is better magic than `spl_object_hash()`. After discussing the problem in [SO php chat](http://chat.stackoverflow.com/rooms/11/php) there was suggestion to just remote that object handlers pointer from hash value generation, so I made this PR - https://github.com/php/php-src/pull/1724. We'll see how it pass or not. I personally don't like both current `spl_object_hash()` inconsistance introduced by changing handlers pointer and also don't like cast to non-const value, mostly because it changes handler globally.

**Comment by colder** [comment]
I have a tentative implementation here that makes spl_object_hash stable here: https://github.com/colder/php-weakref/tree/topic/noconst. I'm quite uncomfortable with it though, so I guess I will wait until your PR gets merged before fixing the const thing.

Another option would be to make hashing a handler itself, which would allow our extensions to override.

**Comment by pinepain** [comment]
JFYI, that PR got merged.

**Comment by pinepain** [comment]
I tried your approach to patch function at runtime and it works in most cases, except `SplObjectHash` uses in it `getHash()` method and `get_debug_info` handler internal `spl_object_hash()` implementation. At this point I'm not sure whether it worth to patch it too or not.
